const ADD = 'ADD';
const CLEAR = 'CLEAR';
const UNDO = 'UNDO';
const ADD_TEXT_TO_HIGHLIGHT = 'ADD_TEXT_TO_HIGHLIGHT';
const RESET = 'RESET';
const ADD_COLOR_TO_FILTER = 'ADD_COLOR_TO_FILTER';

export { ADD, CLEAR, UNDO, ADD_TEXT_TO_HIGHLIGHT, RESET, ADD_COLOR_TO_FILTER };
